### ISSUE TITLE
Google colab cannot pip install

### ISSUE THREAD

**Issue by SamEdwardes** [SamEdwardes/spaCyTextBlob#1]
When I test package on Google Colab it does not work:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/18248949/98900499-beb92180-2466-11eb-8caf-7ade43482ef5.png">

I think I need to lower the version to require at minimum python 3.6.9 instead of 3.8

<img width="252" alt="image" src="https://user-images.githubusercontent.com/18248949/98900537-d4c6e200-2466-11eb-8b86-70c14d3717fd.png">

**Comment by pmdscully** [comment]
`> pip install spacytextblob`
ERROR: Could not find a version that satisfies the requirement spacytextblob
ERROR: No matching distribution found for spacytextblob
`> python --version`
Python 3.6.5 

Or even Occam's until a dependency falls off.

**Comment by SamEdwardes** [comment]
Thanks @pmdscully fixing this is on my to do list. I think I will be able to lower the python requirement to 3.6.5. I have not had a chance to test yet though.

**Comment by SamEdwardes** [comment]
I have changed the python requirements to `python = "^3.6" (5c0733d). I will test on Google Colab as well to see if things work.

**Comment by SamEdwardes** [comment]
Confirmed it now works on colab. Check out: https://colab.research.google.com/drive/1YE9NH5KdvUx8LA78MXAECMKZG0GiAxrn?usp=sharing
