### ISSUE TITLE
Does spacytextblob Support other language like Chinese？

### ISSUE THREAD

**Issue by wushixian** [SamEdwardes/spaCyTextBlob#14]
Because spacy 3 Support Chinese，so I wonder if spacytextblob support Chinese？Or how can I make it Support Chinese?

**Comment by SamEdwardes** [comment]
spaCy has support for many languages. Unfortunately TextBlob only has support for English sentiment analysis at this time (https://github.com/sloria/TextBlob/issues/211).  If TextBlob does eventually create a sentiment analysis model for Chinese it could be used by spaCyTextBlob. Until then only English will work unfortunately .
