### ISSUE TITLE
Mentioning the scores

### ISSUE THREAD

**Issue by vcuspinera** [SamEdwardes/spaCyTextBlob#3]
Congrats Sam, this is a great tool!
I was looking for the meaning of polarity and subjectivity, from one to other place of your references, and found in the [TextBlob tutorial](https://textblob.readthedocs.io/en/latest/quickstart.html#quickstart) that `polarity` score is a float within the range [-1.0, 1.0], and `subjectivity` is a float within the range [0.0, 1.0] where 0.0 is very objective and 1.0 is very subjective. I just recommend you to share this details to the users somewhere in this GitHub repo.

**Comment by SamEdwardes** [comment]
Thanks for the suggestion Victor. Agreed I should add! I will make this update 😄

**Comment by SamEdwardes** [comment]
Closed by #8.
